In [1]:
import numpy as np
import pandas as pd


In [3]:
df = pd.read_csv('homeprices.csv')
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

## Using pandas library 

- using the pandas library we can create dummy data in categorical data
- 

In [6]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [10]:
merged = pd.concat([df,dummies],axis = 'columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [12]:
final  = merged.drop(['town'],axis='columns')
final

area   price  monroe township  robinsville  west windsor
0   2600  550000             True        False         False
1   3000  565000             True        False         False
2   3200  610000             True        False         False
3   3600  680000             True        False         False
4   4000  725000             True        False         False
5   2600  585000            False        False          True
6   2800  615000            False        False          True
7   3300  650000            False        False          True
8   3600  710000            False        False          True
9   2600  575000            False         True         False
10  2900  600000            False         True         False
11  3100  620000            False         True         False
12  3600  695000            False         True         False

- in here we can drop a one column from dummy columns because sklearn will know what columns they want and do not want

In [21]:
final = final.drop(['west windsor'],axis='columns')
final.head()

area   price  monroe township  robinsville
0  2600  550000             True        False
1  3000  565000             True        False
2  3200  610000             True        False
3  3600  680000             True        False
4  4000  725000             True        False

In [23]:
x = final.drop(['price'],axis='columns')
x.head()

area  monroe township  robinsville
0  2600             True        False
1  3000             True        False
2  3200             True        False
3  3600             True        False
4  4000             True        False

In [25]:
y = final.price
y.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [29]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [31]:
model.fit(x,y)

LinearRegression()

In [33]:
model.predict([[3400,0,0]])

C:\Users\sdara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [35]:
model.predict([[2800,0,1]])

C:\Users\sdara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

## Using the SKlearn onehot encoding 

In [101]:
df = pd.read_csv('homeprices.csv')
df.head()



town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [107]:
x = df.drop(['town'],axis='columns')
x


area   price
0   2600  550000
1   3000  565000
2   3200  610000
3   3600  680000
4   4000  725000
5   2600  585000
6   2800  615000
7   3300  650000
8   3600  710000
9   2600  575000
10  2900  600000
11  3100  620000
12  3600  695000

In [111]:
y = df.town
y

0     monroe township
1     monroe township
2     monroe township
3     monroe township
4     monroe township
5        west windsor
6        west windsor
7        west windsor
8        west windsor
9         robinsville
10        robinsville
11        robinsville
12        robinsville
Name: town, dtype: object

In [119]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()    # convert names in to numbers


In [121]:
dfle =  df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [123]:
x = dfle[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [131]:
y = dfle['price']
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

Now use one hot encoder to create dummy variables for each of the town

In [153]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(categories=[0])
ohe

OneHotEncoder(categories=[0])

In [157]:
x = x[:,1:]
x

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [145]:
model.fit(x,y)

LinearRegression()

In [147]:
model.predict([[0,1,3400]])

ValueError: X has 3 features, but LinearRegression is expecting 11 features as input.